

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pytest
    displayName: 'Install dependencies'

  - script: |
      pytest
    displayName: 'Run tests'

  - script: |
      python hello.py
    displayName: 'Run application'

  - task: CopyFiles@2
    inputs:
      contents: 'hello.py'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'

  - script: |
      chmod +x deploy.sh
      ./deploy.sh
    displayName: 'Deploy application'